name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: |
            21
            11
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon -Dorg.gradle.java.home="$JAVA_HOME_21_X64"