name: Release
on:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: |
            21
            11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon -Dorg.gradle.java.home="$JAVA_HOME_21_X64" -Prelease=${{  github.ref_name }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/libs/mclogs-fabric-*.jar
          body_path: ${{ github.workspace }}/CHANGELOG.md
          name: v${{ github.ref_name }}
      - name: Publish to Modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew modrinth --no-daemon -Dorg.gradle.java.home="$JAVA_HOME_21_X64" -Prelease=${{  github.ref_name }}
      - name: Publish to CurseForge
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        run: ./gradlew publishCurseforge --no-daemon -Dorg.gradle.java.home="$JAVA_HOME_21_X64" -Prelease=${{  github.ref_name }}